### ISSUE TITLE
Call with no arguments errors

### ISSUE THREAD

**Issue by zmoon** [nschloe/deadlink#34]
It could be more graceful, either printing the help or doing nothing.

Currently get:
```
...
... deadlink\_cli.py", line 53, in cli
    return args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'
```

v0.4.7

**Comment by nschloe** [comment]
Fixed in 0.4.8. Thanks for the report!

**Comment by zmoon** [comment]
Hi @nschloe, thanks for the quick response. This fix gives an error for me in Python 3.7.11 though.
```
❯ deadlink
Traceback (most recent call last):
  File "c:\programdata\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\zmoon\.local\bin\deadlink.exe\__main__.py", line 7, in <module>
  File "C:\Users\zmoon\.local\pipx\venvs\deadlink\lib\site-packages\deadlink\_cli.py", line 52, in cli
    args = parser.parse_args(argv)
  File "c:\programdata\miniconda3\lib\argparse.py", line 1755, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "c:\programdata\miniconda3\lib\argparse.py", line 1787, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "c:\programdata\miniconda3\lib\argparse.py", line 2022, in _parse_known_args
    ', '.join(required_actions))
TypeError: sequence item 0: expected str instance, NoneType found
```

**Comment by nschloe** [comment]
No idea why that should be. [`required` was added to `add_subparsers` in 3.7.](https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.add_subparsers)

**Comment by zmoon** [comment]
Yeah, well here is a possible workaround that I tested it to work in 3.7 and 3.8.

```python
# in _cli.cli
if argv is None and version_info < (3, 9):
    argv = " "
```

**Comment by nschloe** [comment]
The issue was actually [this Python bug](https://bugs.python.org/issue29298). I've worked around it now, should be good.

**Comment by zmoon** [comment]
Cool, and thanks for sharing the link! I do think my 2nd workaround might have been a bit better, providing a more helpful message more in line with the 3.9/10 behavior / that fix you linked, and avoiding `deadlink: error: the following arguments are required: func`, which is slightly less clear and the name `func` a bit non-standard in such command-line context.
